In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#importing the  train data 
data=pd.read_csv("train.csv")
data.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  Accident_ID  
0   31335.476824           3                0.424352         7570  
1   26024.711057           2                0.352350        12128  
2   39269.053927           3                0.003364         2181  
3   42771.499200           1                0.211728         5946  
4   35509.228515           2                0.176883         9054

In [3]:
#Checking some null values in the data
data.isnull().sum()

Severity                   0
Safety_Score               0
Days_Since_Inspection      0
Total_Safety_Complaints    0
Control_Metric             0
Turbulence_In_gforces      0
Cabin_Temperature          0
Accident_Type_Code         0
Max_Elevation              0
Violations                 0
Adverse_Weather_Metric     0
Accident_ID                0
dtype: int64

In [4]:
data.Accident_Type_Code.nunique()

7

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
Severity                   10000 non-null object
Safety_Score               10000 non-null float64
Days_Since_Inspection      10000 non-null int64
Total_Safety_Complaints    10000 non-null int64
Control_Metric             10000 non-null float64
Turbulence_In_gforces      10000 non-null float64
Cabin_Temperature          10000 non-null float64
Accident_Type_Code         10000 non-null int64
Max_Elevation              10000 non-null float64
Violations                 10000 non-null int64
Adverse_Weather_Metric     10000 non-null float64
Accident_ID                10000 non-null int64
dtypes: float64(6), int64(5), object(1)
memory usage: 937.6+ KB


In [6]:
#There is multiclass problem having 7 different classes

In [7]:
X=data.loc[:,["Safety_Score","Days_Since_Inspection","Total_Safety_Complaints","Control_Metric","Turbulence_In_gforces","Cabin_Temperature","Max_Elevation","Violations","Adverse_Weather_Metric"]].values
y=data.loc[:,"Accident_Type_Code"].values

In [8]:
X

array([[4.92237443e+01, 1.40000000e+01, 2.20000000e+01, ...,
        3.13354768e+04, 3.00000000e+00, 4.24352083e-01],
       [6.24657534e+01, 1.00000000e+01, 2.70000000e+01, ...,
        2.60247111e+04, 2.00000000e+00, 3.52349973e-01],
       [6.30593607e+01, 1.30000000e+01, 1.60000000e+01, ...,
        3.92690539e+04, 3.00000000e+00, 3.36390699e-03],
       ...,
       [2.78538813e+01, 1.70000000e+01, 1.00000000e+00, ...,
        3.37719963e+04, 3.00000000e+00, 1.68173043e-01],
       [5.62100457e+01, 8.00000000e+00, 0.00000000e+00, ...,
        3.98204193e+04, 2.00000000e+00, 2.63809289e-02],
       [5.00000000e+01, 1.30000000e+01, 3.00000000e+00, ...,
        2.60053230e+04, 2.00000000e+00, 1.70358910e-02]])

In [9]:
y

array([2, 2, 7, ..., 3, 5, 5])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [11]:
#first we are using simple svm  
test_data=pd.read_csv("test.csv")
test_data

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0        19.497717                     16                        6   
1        58.173516                     15                        3   
2        33.287671                     15                        3   
3         3.287671                     21                        5   
4        10.867580                     18                        2   
...            ...                    ...                      ...   
2495     68.127854                      8                       11   
2496     54.840183                      9                        9   
2497     36.712329                     14                       10   
2498     38.721461                     13                       14   
2499     36.073059                     11                        1   

      Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0          72.151322               0.388959              78.32   
1          64.585232               0.250841              78.60   
2          64.721969               0.336669              86.96   
3          66.362808               0.421775              80.86   
4          56.107566               0.313228              79.22   
...              ...                    ...                ...   
2495       49.680948               0.470819              77.80   
2496       71.194166               0.417087              79.77   
2497       91.203282               0.313950              83.96   
2498       73.154057               0.275003              77.38   
2499       60.665451               0.256250              84.56   

      Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                      4   37949.724386           2                0.069692   
1                      7   30194.805567           2                0.002777   
2                      6   17572.925484           1                0.004316   
3                      3   40209.186341           2                0.199990   
4                      2   35495.525408           2                0.483696   
...                  ...            ...         ...                     ...   
2495                   2   48251.586622           2                0.659387   
2496                   6   20761.984416           1                0.005010   
2497                   6   36676.100601           2                0.008629   
2498                   6   24211.359510           1                0.006247   
2499                   5   35920.146239           0                0.024409   

      Accident_ID  
0               1  
1              10  
2              14  
3              17  
4              21  
...           ...  
2495        12484  
2496        12487  
2497        12488  
2498        12491  
2499        12493  

[2500 rows x 11 columns]

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(X_train)
sc.transform(X_test)

array([[-0.66591755, -0.25845514, -0.65795842, ...,  0.16738708,
        -0.01022622,  2.55672829],
       [ 0.73186124, -1.10677618, -0.65795842, ...,  1.49167664,
         0.95224165, -0.0662162 ],
       [ 0.46818289,  0.02431854, -0.65795842, ...,  0.76921344,
        -1.93516196,  0.7103697 ],
       ...,
       [-0.01664505,  0.02431854,  1.06642073, ...,  1.15402395,
        -0.97269409, -0.59258949],
       [-0.62905929, -0.25845514, -0.65795842, ..., -0.32871402,
        -0.01022622, -0.52857766],
       [-0.20944213,  0.02431854,  0.20423116, ...,  0.26242034,
        -0.97269409, -0.21885601]])

In [13]:
from sklearn.svm import SVC
classifier=SVC(kernel="rbf",random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [14]:
y_pred=classifier.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[  0,   0,   0, 240,   0,   0,   0],
       [  0,   4,   0, 349,   0,   0,   0],
       [  0,   1,   0, 373,   0,   0,   0],
       [  0,   1,   0, 409,   0,   0,   0],
       [  0,   0,   0, 156,   0,   0,   0],
       [  0,   0,   0, 238,   0,   0,   0],
       [  0,   2,   0, 227,   0,   0,   0]])

In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       240
           2       0.50      0.01      0.02       353
           3       0.00      0.00      0.00       374
           4       0.21      1.00      0.34       410
           5       0.00      0.00      0.00       156
           6       0.00      0.00      0.00       238
           7       0.00      0.00      0.00       229

    accuracy                           0.21      2000
   macro avg       0.10      0.14      0.05      2000
weighted avg       0.13      0.21      0.07      2000



/home/tarun/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
print(accuracy_score(y_test,y_pred))

0.2065


In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [19]:
y_pred=classifier.predict(X_test)

In [20]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[240,   0,   0,   0,   0,   0,   0],
       [  0, 352,   1,   0,   0,   0,   0],
       [  0,   2, 371,   1,   0,   0,   0],
       [  0,   0,   0, 409,   0,   0,   1],
       [  0,   0,   0,   2, 152,   2,   0],
       [  0,   0,   0,   0,   1, 234,   3],
       [  0,   0,   0,   0,   0,   0, 229]])

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       240
           2       0.99      1.00      1.00       353
           3       1.00      0.99      0.99       374
           4       0.99      1.00      1.00       410
           5       0.99      0.97      0.98       156
           6       0.99      0.98      0.99       238
           7       0.98      1.00      0.99       229

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [22]:
print(accuracy_score(y_test,y_pred))

0.9935


In [23]:
from sklearn.ensemble import GradientBoostingClassifier
classifier=GradientBoostingClassifier()
classifier.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [24]:
y_pred=classifier.predict(X_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[240   0   0   0   0   0   0]
 [  0 353   0   0   0   0   0]
 [  0   0 373   1   0   0   0]
 [  0   0   0 410   0   0   0]
 [  0   0   0   1 153   2   0]
 [  0   0   0   0   0 235   3]
 [  0   0   0   0   0   0 229]]


In [25]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       240
           2       1.00      1.00      1.00       353
           3       1.00      1.00      1.00       374
           4       1.00      1.00      1.00       410
           5       1.00      0.98      0.99       156
           6       0.99      0.99      0.99       238
           7       0.99      1.00      0.99       229

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000



In [26]:
print(accuracy_score(y_test,y_pred))

0.9965


In [27]:
#Now we can test on test data
test_data.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [28]:
X_new_test=test_data.loc[:,["Safety_Score","Days_Since_Inspection","Total_Safety_Complaints","Control_Metric","Turbulence_In_gforces","Cabin_Temperature","Max_Elevation","Violations","Adverse_Weather_Metric"]].values
y_new_test=test_data.loc[:,"Accident_Type_Code"].values

In [29]:
y_pred=classifier.predict(X_new_test)

In [30]:
cm=confusion_matrix(y_new_test,y_pred)
cm

array([[282,   0,   0,   0,   0,   0,   0],
       [  0, 405,   2,   0,   0,   0,   0],
       [  0,   0, 450,   0,   0,   0,   0],
       [  0,   0,   0, 547,   1,   0,   0],
       [  0,   0,   0,   1, 200,   2,   0],
       [  0,   0,   0,   0,   1, 285,   3],
       [  0,   0,   0,   0,   0,   0, 321]])

In [31]:
print(classification_report(y_new_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00       282
           2       1.00      1.00      1.00       407
           3       1.00      1.00      1.00       450
           4       1.00      1.00      1.00       548
           5       0.99      0.99      0.99       203
           6       0.99      0.99      0.99       289
           7       0.99      1.00      1.00       321

    accuracy                           1.00      2500
   macro avg       1.00      0.99      1.00      2500
weighted avg       1.00      1.00      1.00      2500



In [32]:
print(accuracy_score(y_new_test,y_pred))

0.996


In [33]:
data.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  Accident_ID  
0   31335.476824           3                0.424352         7570  
1   26024.711057           2                0.352350        12128  
2   39269.053927           3                0.003364         2181  
3   42771.499200           1                0.211728         5946  
4   35509.228515           2                0.176883         9054

In [34]:
data.Severity.unique()

array(['Minor_Damage_And_Injuries', 'Significant_Damage_And_Fatalities',
       'Significant_Damage_And_Serious_Injuries',
       'Highly_Fatal_And_Damaging'], dtype=object)

In [35]:
#Multiclass problem

In [36]:
#creating a dict file
Sub_topic={'Minor_Damage_And_Injuries':1,'Significant_Damage_And_Fatalities':2,'Significant_Damage_And_Serious_Injuries':3,'Highly_Fatal_And_Damaging':4}
data.Severity=[Sub_topic[i] for i in data.Severity]

In [37]:
data.head()

Severity  Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0         1     49.223744                     14                       22   
1         1     62.465753                     10                       27   
2         2     63.059361                     13                       16   
3         3     48.082192                     11                        9   
4         2     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118              78.04   
1       72.288058               0.423939              84.54   
2       66.362808               0.322604              78.86   
3       74.703737               0.337029              81.79   
4       47.948952               0.541140              77.16   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   2   31335.476824           3                0.424352   
1                   2   26024.711057           2                0.352350   
2                   7   39269.053927           3                0.003364   
3                   3   42771.499200           1                0.211728   
4                   3   35509.228515           2                0.176883   

   Accident_ID  
0         7570  
1        12128  
2         2181  
3         5946  
4         9054

In [38]:
def fah_to_cel(x):
    x=((x-32)*5/9)
    return x
fah_to_cel(98.6)

37.0

In [39]:
data["Cabin_Temperature"]=data["Cabin_Temperature"].apply(fah_to_cel)

In [40]:
data.head()

Severity  Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0         1     49.223744                     14                       22   
1         1     62.465753                     10                       27   
2         2     63.059361                     13                       16   
3         3     48.082192                     11                        9   
4         2     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118          25.577778   
1       72.288058               0.423939          29.188889   
2       66.362808               0.322604          26.033333   
3       74.703737               0.337029          27.661111   
4       47.948952               0.541140          25.088889   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   2   31335.476824           3                0.424352   
1                   2   26024.711057           2                0.352350   
2                   7   39269.053927           3                0.003364   
3                   3   42771.499200           1                0.211728   
4                   3   35509.228515           2                0.176883   

   Accident_ID  
0         7570  
1        12128  
2         2181  
3         5946  
4         9054

In [41]:
#Now you just have to predict the Severity
X=data.iloc[:,[1,2,3,4,5,6,7,8,9,10]].values
y=data.iloc[:,0].values

In [42]:
X.shape

(10000, 10)

In [ ]:
from sklearn.model_selection import RepeatedKFold
rkf = RepeatedKFold(n_splits=5, n_repeats=10, random_state=None)
# X is the feature set and y is the target
for train_index, test_index in rkf.split(X):
     print("Train:", train_index, "Validation:", val_index)
     X_train, X_test = X[train_index], X[val_index]
     y_train, y_test = y[train_index], y[val_index]

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(X_train)
sc.transform(X_test)

array([[-0.66591755, -0.25845514, -0.65795842, ...,  0.16738708,
        -0.01022622,  2.55672829],
       [ 0.73186124, -1.10677618, -0.65795842, ...,  1.49167664,
         0.95224165, -0.0662162 ],
       [ 0.46818289,  0.02431854, -0.65795842, ...,  0.76921344,
        -1.93516196,  0.7103697 ],
       ...,
       [-0.01664505,  0.02431854,  1.06642073, ...,  1.15402395,
        -0.97269409, -0.59258949],
       [-0.62905929, -0.25845514, -0.65795842, ..., -0.32871402,
        -0.01022622, -0.52857766],
       [-0.20944213,  0.02431854,  0.20423116, ...,  0.26242034,
        -0.97269409, -0.21885601]])

In [45]:
classifier=SVC(kernel="rbf",random_state=0,C=1)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [46]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[  0,   0,   0, 493],
       [  0,   0,   0, 312],
       [  0,   0,   0, 575],
       [  0,   0,   0, 620]])

In [47]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       493
           2       0.00      0.00      0.00       312
           3       0.00      0.00      0.00       575
           4       0.31      1.00      0.47       620

    accuracy                           0.31      2000
   macro avg       0.08      0.25      0.12      2000
weighted avg       0.10      0.31      0.15      2000



/home/tarun/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1268: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=15,n_jobs=-1,metric='minkowski',p=3)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [49]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[190  43 139 121]
 [ 89  58  72  93]
 [164  51 216 144]
 [139  59 148 274]]


In [50]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.33      0.39      0.35       493
           2       0.27      0.19      0.22       312
           3       0.38      0.38      0.38       575
           4       0.43      0.44      0.44       620

    accuracy                           0.37      2000
   macro avg       0.35      0.35      0.35      2000
weighted avg       0.37      0.37      0.37      2000



In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [52]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[190  43 139 121]
 [ 89  58  72  93]
 [164  51 216 144]
 [139  59 148 274]]


In [53]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.33      0.39      0.35       493
           2       0.27      0.19      0.22       312
           3       0.38      0.38      0.38       575
           4       0.43      0.44      0.44       620

    accuracy                           0.37      2000
   macro avg       0.35      0.35      0.35      2000
weighted avg       0.37      0.37      0.37      2000



In [54]:
classifier=GradientBoostingClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [55]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[437  26  20  10]
 [  9 273  14  16]
 [ 47   4 508  16]
 [ 70  16  14 520]]


In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.78      0.89      0.83       493
           2       0.86      0.88      0.87       312
           3       0.91      0.88      0.90       575
           4       0.93      0.84      0.88       620

    accuracy                           0.87      2000
   macro avg       0.87      0.87      0.87      2000
weighted avg       0.87      0.87      0.87      2000



In [88]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
classifier=BaggingClassifier(n_estimators=500,random_state=0)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [74]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[470   6   5  12]
 [  5 298   6   3]
 [ 21   2 538  14]
 [  6  15  13 586]]


In [75]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.94      0.95      0.94       493
           2       0.93      0.96      0.94       312
           3       0.96      0.94      0.95       575
           4       0.95      0.95      0.95       620

    accuracy                           0.95      2000
   macro avg       0.94      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000



In [76]:
data.head()

Severity  Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0         1     49.223744                     14                       22   
1         1     62.465753                     10                       27   
2         2     63.059361                     13                       16   
3         3     48.082192                     11                        9   
4         2     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118          25.577778   
1       72.288058               0.423939          29.188889   
2       66.362808               0.322604          26.033333   
3       74.703737               0.337029          27.661111   
4       47.948952               0.541140          25.088889   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   2   31335.476824           3                0.424352   
1                   2   26024.711057           2                0.352350   
2                   7   39269.053927           3                0.003364   
3                   3   42771.499200           1                0.211728   
4                   3   35509.228515           2                0.176883   

   Accident_ID  
0         7570  
1        12128  
2         2181  
3         5946  
4         9054

In [77]:
test_data.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [78]:
test= test_data.iloc[ : ,[0,1,2,3,4,5,6,7,8,9]].values
test_data_id=test_data.iloc[:,10].values

In [63]:
#predictin on the test data

In [79]:
y_pred=classifier.predict(test)

In [80]:
y_pred=pd.DataFrame({'Severity':y_pred})

In [81]:
y_pred

Severity
0            4
1            2
2            3
3            4
4            2
...        ...
2495         4
2496         3
2497         3
2498         3
2499         4

[2500 rows x 1 columns]

In [82]:
#creating a dict file
another_Sub_topic={ 1 : 'Minor_Damage_And_Injuries', 2 : 'Significant_Damage_And_Fatalities' , 3 : 'Significant_Damage_And_Serious_Injuries', 4 : 'Highly_Fatal_And_Damaging'}
y_pred.Severity=[another_Sub_topic[i] for i in y_pred.Severity]

In [83]:
y_pred["Accident_ID"]=test_data_id

In [84]:
y_pred

Severity  Accident_ID
0                   Highly_Fatal_And_Damaging            1
1           Significant_Damage_And_Fatalities           10
2     Significant_Damage_And_Serious_Injuries           14
3                   Highly_Fatal_And_Damaging           17
4           Significant_Damage_And_Fatalities           21
...                                       ...          ...
2495                Highly_Fatal_And_Damaging        12484
2496  Significant_Damage_And_Serious_Injuries        12487
2497  Significant_Damage_And_Serious_Injuries        12488
2498  Significant_Damage_And_Serious_Injuries        12491
2499                Highly_Fatal_And_Damaging        12493

[2500 rows x 2 columns]

In [85]:
y_pred.set_index('Accident_ID',inplace=True)

In [86]:
y_pred.head()

Severity
Accident_ID                                         
1                          Highly_Fatal_And_Damaging
10                 Significant_Damage_And_Fatalities
14           Significant_Damage_And_Serious_Injuries
17                         Highly_Fatal_And_Damaging
21                 Significant_Damage_And_Fatalities

In [87]:
y_pred.to_csv("Submission.csv")

ImportError: cannot import name 'Sequential' from 'keras.layers' (/home/tarun/anaconda3/lib/python3.7/site-packages/keras/layers/__init__.py)